In [2]:
import numpy as np 
import pandas as pd

In [3]:
train=pd.read_csv("D:\Downloads/Train_eP48B9k.csv")
test=pd.read_csv("D:\Downloads/Test_jPKyvmK.csv")

In [4]:
train.shape

(31647, 18)

In [5]:
train.tail(5)

id  customer_age    job_type  marital  education default  \
31642  id_27290          58.0      admin.  married  secondary      no   
31643  id_20428          51.0  management  married   tertiary      no   
31644  id_44679          41.0  unemployed  married    primary      no   
31645   id_4841          48.0    services  married  secondary      no   
31646   id_1723          38.0  technician   single   tertiary      no   

       balance housing_loan personal_loan communication_type  day_of_month  \
31642    567.0          yes            no           cellular             2   
31643   1072.0           no            no            unknown            20   
31644    242.0          yes            no            unknown            23   
31645   2699.0           no            no           cellular            11   
31646   1045.0           no            no           cellular            18   

      month  last_contact_duration  num_contacts_in_campaign  \
31642   feb                   99.0                       2.0   
31643   jun                   31.0                       7.0   
31644   may                   89.0                       2.0   
31645   aug                  216.0                       6.0   
31646   aug                  183.0                      10.0   

       days_since_prev_campaign_contact  num_contacts_prev_campaign  \
31642                             265.0                           3   
31643                               NaN                           0   
31644                               NaN                           0   
31645                               NaN                           0   
31646                               NaN                           0   

      prev_campaign_outcome  term_deposit_subscribed  
31642                 other                        0  
31643               unknown                        0  
31644               unknown                        0  
31645               unknown                        0  
31646               unknown                        0

In [6]:
test.shape

(13564, 17)

In [7]:
df=pd.concat([train,test],axis=0,sort=False)

In [8]:
df.head()

id  customer_age     job_type  marital  education default  balance  \
0  id_43823          28.0   management   single   tertiary      no    285.0   
1  id_32289          34.0  blue-collar  married  secondary      no    934.0   
2  id_10523          46.0   technician  married  secondary      no    656.0   
3  id_43951          34.0     services   single  secondary      no      2.0   
4  id_40992          41.0  blue-collar  married    primary      no   1352.0   

  housing_loan personal_loan communication_type  day_of_month month  \
0          yes            no            unknown            26   jun   
1           no           yes           cellular            18   nov   
2           no            no           cellular             5   feb   
3          yes            no            unknown            20   may   
4          yes            no           cellular            13   may   

   last_contact_duration  num_contacts_in_campaign  \
0                  303.0                       4.0   
1                  143.0                       2.0   
2                  101.0                       4.0   
3                  127.0                       3.0   
4                   49.0                       2.0   

   days_since_prev_campaign_contact  num_contacts_prev_campaign  \
0                               NaN                           0   
1                             132.0                           1   
2                               NaN                           0   
3                               NaN                           0   
4                               NaN                           0   

  prev_campaign_outcome  term_deposit_subscribed  
0               unknown                      0.0  
1                 other                      0.0  
2               unknown                      0.0  
3               unknown                      0.0  
4               unknown                      0.0

In [9]:
df.isnull().any()

id                                  False
customer_age                         True
job_type                            False
marital                              True
education                           False
default                             False
balance                              True
housing_loan                        False
personal_loan                        True
communication_type                  False
day_of_month                        False
month                               False
last_contact_duration                True
num_contacts_in_campaign             True
days_since_prev_campaign_contact     True
num_contacts_prev_campaign          False
prev_campaign_outcome               False
term_deposit_subscribed              True
dtype: bool

In [10]:
df.describe()

customer_age        balance  day_of_month  last_contact_duration  \
count  44322.000000   44631.000000  45211.000000           44778.000000   
mean      40.442579    1360.104255     15.806419             257.681093   
std       10.750219    3013.771829      8.322476             257.704129   
min       18.000000   -8020.000000      1.000000               0.000000   
25%       32.000000      71.000000      8.000000             102.000000   
50%       39.000000     448.000000     16.000000             180.000000   
75%       48.000000    1427.000000     21.000000             319.000000   
max       97.000000  102128.000000     31.000000            4900.000000   

       num_contacts_in_campaign  days_since_prev_campaign_contact  \
count              45054.000000                       8257.000000   
mean                   2.762929                        224.577692   
std                    3.091258                        115.344035   
min                    1.000000                          1.000000   
25%                    1.000000                        133.000000   
50%                    2.000000                        194.000000   
75%                    3.000000                        327.000000   
max                   63.000000                        871.000000   

       num_contacts_prev_campaign  term_deposit_subscribed  
count                45211.000000             31647.000000  
mean                     0.580323                 0.107246  
std                      2.303441                 0.309430  
min                      0.000000                 0.000000  
25%                      0.000000                 0.000000  
50%                      0.000000                 0.000000  
75%                      0.000000                 0.000000  
max                    275.000000                 1.000000

In [11]:
df['customer_age']=df['customer_age'].fillna(df['customer_age'].median())

In [12]:
df['customer_age'].isnull().any()

False

In [13]:
df.isnull().sum()

id                                      0
customer_age                            0
job_type                                0
marital                               231
education                               0
default                                 0
balance                               580
housing_loan                            0
personal_loan                         223
communication_type                      0
day_of_month                            0
month                                   0
last_contact_duration                 433
num_contacts_in_campaign              157
days_since_prev_campaign_contact    36954
num_contacts_prev_campaign              0
prev_campaign_outcome                   0
term_deposit_subscribed             13564
dtype: int64

In [14]:
df['marital'].mode()

0    married
dtype: object

In [15]:
df['marital'].value_counts()

married     27068
single      12726
divorced     5186
Name: marital, dtype: int64

In [16]:
df['marital']=df['marital'].fillna('married')

In [17]:
df['marital'].isnull().any()

False

In [18]:
df['balance']=df['balance'].fillna(df['balance'].mean())

In [19]:
df['balance'].isnull().any()

False

In [20]:
df.isnull().sum()

id                                      0
customer_age                            0
job_type                                0
marital                                 0
education                               0
default                                 0
balance                                 0
housing_loan                            0
personal_loan                         223
communication_type                      0
day_of_month                            0
month                                   0
last_contact_duration                 433
num_contacts_in_campaign              157
days_since_prev_campaign_contact    36954
num_contacts_prev_campaign              0
prev_campaign_outcome                   0
term_deposit_subscribed             13564
dtype: int64

In [21]:
df['personal_loan'].mode()

0    no
dtype: object

In [22]:
df['personal_loan']=df['personal_loan'].fillna('no')

In [23]:
df['personal_loan'].isnull().any()

False

In [24]:
 df['last_contact_duration']= df['last_contact_duration'].fillna( df['last_contact_duration'].median())

In [25]:
 df['last_contact_duration'].isnull().any()

False

In [26]:
df['num_contacts_in_campaign'].value_counts()

1.0     17489
2.0     12454
3.0      5502
4.0      3510
5.0      1758
6.0      1289
7.0       732
8.0       539
9.0       326
10.0      265
11.0      201
12.0      154
13.0      132
14.0       93
15.0       83
16.0       78
17.0       68
18.0       51
19.0       44
20.0       43
21.0       35
22.0       23
25.0       22
23.0       22
24.0       20
28.0       16
29.0       16
26.0       13
31.0       12
27.0       10
32.0        9
30.0        8
33.0        6
34.0        5
36.0        4
35.0        4
38.0        3
43.0        3
41.0        2
37.0        2
50.0        1
63.0        1
51.0        1
46.0        1
58.0        1
44.0        1
55.0        1
39.0        1
Name: num_contacts_in_campaign, dtype: int64

In [27]:
df['num_contacts_in_campaign'] = df['num_contacts_in_campaign'].fillna(1)

In [28]:
df['num_contacts_in_campaign'].isnull().any()

False

In [29]:
drop=['id','days_since_prev_campaign_contact']
df=df.drop(drop,axis=1)


In [30]:
df.columns

Index(['customer_age', 'job_type', 'marital', 'education', 'default',
       'balance', 'housing_loan', 'personal_loan', 'communication_type',
       'day_of_month', 'month', 'last_contact_duration',
       'num_contacts_in_campaign', 'num_contacts_prev_campaign',
       'prev_campaign_outcome', 'term_deposit_subscribed'],
      dtype='object')

In [31]:
df['prev_campaign_outcome'].value_counts()

unknown    36959
failure     4901
other       1840
success     1511
Name: prev_campaign_outcome, dtype: int64

In [32]:
df=df.drop('prev_campaign_outcome',axis=1)

In [33]:
df['communication_type'].value_counts()

cellular     29285
unknown      13020
telephone     2906
Name: communication_type, dtype: int64

In [34]:
df['default']=df['default'].map({'no':0,'yes':1})
df['housing_loan']=df['housing_loan'].map({'no':0,'yes':1})
df['personal_loan']=df['personal_loan'].map({'no':0,'yes':1})
df['communication_type']=df['communication_type'].map({'cellular':0,'unknown':1,'telephone':2})

In [35]:
df = pd.get_dummies(df)

In [36]:
df['is_old']=1
df.loc[df['customer_age'] <= 50, 'is_old'] = 0

In [37]:
df.columns

Index(['customer_age', 'default', 'balance', 'housing_loan', 'personal_loan',
       'communication_type', 'day_of_month', 'last_contact_duration',
       'num_contacts_in_campaign', 'num_contacts_prev_campaign',
       'term_deposit_subscribed', 'job_type_admin.', 'job_type_blue-collar',
       'job_type_entrepreneur', 'job_type_housemaid', 'job_type_management',
       'job_type_retired', 'job_type_self-employed', 'job_type_services',
       'job_type_student', 'job_type_technician', 'job_type_unemployed',
       'job_type_unknown', 'marital_divorced', 'marital_married',
       'marital_single', 'education_primary', 'education_secondary',
       'education_tertiary', 'education_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'is_old'],
      dtype='object')

In [38]:
train_set=df.iloc[:31647,:]
test_set=df.iloc[31647:,:]

In [39]:
train_set.tail(5)

customer_age  default  balance  housing_loan  personal_loan  \
31642          58.0        0    567.0             1              0   
31643          51.0        0   1072.0             0              0   
31644          41.0        0    242.0             1              0   
31645          48.0        0   2699.0             0              0   
31646          38.0        0   1045.0             0              0   

       communication_type  day_of_month  last_contact_duration  \
31642                   0             2                   99.0   
31643                   1            20                   31.0   
31644                   1            23                   89.0   
31645                   0            11                  216.0   
31646                   0            18                  183.0   

       num_contacts_in_campaign  num_contacts_prev_campaign  ...  month_feb  \
31642                       2.0                           3  ...          1   
31643                       7.0                           0  ...          0   
31644                       2.0                           0  ...          0   
31645                       6.0                           0  ...          0   
31646                      10.0                           0  ...          0   

       month_jan  month_jul  month_jun  month_mar  month_may  month_nov  \
31642          0          0          0          0          0          0   
31643          0          0          1          0          0          0   
31644          0          0          0          0          1          0   
31645          0          0          0          0          0          0   
31646          0          0          0          0          0          0   

       month_oct  month_sep  is_old  
31642          0          0       1  
31643          0          0       1  
31644          0          0       0  
31645          0          0       0  
31646          0          0       0  

[5 rows x 43 columns]

In [40]:
X_train=train_set.drop('term_deposit_subscribed',axis=1)
y_train=train_set['term_deposit_subscribed']
X_test=test_set.drop('term_deposit_subscribed',axis=1)

In [41]:
from sklearn.model_selection import StratifiedKFold
skfolds = StratifiedKFold(n_splits=3, random_state=42)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:297: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [42]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier()


In [48]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer
from sklearn.metrics import f1_score
cross_val_score(rnd_clf, X_train, y_train, cv=skfolds, scoring=make_scorer(f1_score))

array([0.46013667, 0.47266703, 0.46939921])

In [49]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(penalty='l2',dual=False,max_iter=100)
cross_val_score(lr,X_train,y_train,cv=3,scoring=make_scorer(f1_score))

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

array([0.3018617 , 0.33945535, 0.30877643])

In [52]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()
cross_val_score(tree_clf, X_train, y_train, cv=skfolds, scoring=make_scorer(f1_score))

array([0.49194602, 0.46939674, 0.48885002])

In [53]:
from sklearn.ensemble import AdaBoostClassifier
ada_clf= AdaBoostClassifier()
cross_val_score(ada_clf,X_train,y_train,cv=skfolds,scoring=make_scorer(f1_score))

array([0.44395604, 0.42728298, 0.43478261])

In [54]:
from sklearn.model_selection import RandomizedSearchCV
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

D:\Anaconda\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
D:\Anaconda\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)


In [55]:
lgbm_clf=LGBMClassifier()
cross_val_score(lgbm_clf,X_train,y_train,cv=skfolds,scoring=make_scorer(f1_score))

array([0.56513222, 0.5631253 , 0.57240371])

In [63]:
xgb_clf =XGBClassifier()
cross_val_score(xgb_clf,X_train,y_train,cv=3,scoring=make_scorer(f1_score))

array([0.55352738, 0.55718475, 0.55182482])

In [64]:
pred=lgbm_clf.fit(X_train,y_train).predict(X_test)

In [65]:
df1 = pd.DataFrame(data = pred,columns=["term_deposit_subscribed"])

In [66]:
df1.head()

term_deposit_subscribed
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0

In [67]:
df1["term_deposit_subscribed"] = df1["term_deposit_subscribed"].astype(int)

In [68]:
sample=pd.read_csv("D:\Downloads/SampleSubmission_XkIpo3X.csv")

In [70]:
sub = pd.concat([sample["id"],df1],axis=1)

In [71]:
sub.to_csv("submission1_bank_marketing.csv",index=False)

In [78]:
n_estimators = [300,150,450,200,500]
max_depth = ["None",4,5,6,7,8,10,20,30,40]
learning_rate=["0.1","0.2","0.5","0.3","0.01"]
# max_features = ["auto",0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
min_child_samples=["20","10","5","30"]
# min_samples_split = [2,5,10,15,20,25]
min_samples_leaf = [1,2,5,10,15]

param_grid = dict(n_estimators = n_estimators,max_depth=max_depth,learning_rate=learning_rate,
                  min_child_samples=min_child_samples)


In [79]:
import time
rand=RandomizedSearchCV(estimator=lgbm_clf,param_distributions=param_grid,cv =skfolds)
start_time = time.time()
rand_result = rand.fit(X_train,y_train)

print(f"Best: {rand_result.best_score_} using {rand_result.best_params_}" )
print(f"Execution time: {str((time.time() - start_time))} ms")

[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max

D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda\lib\site-packages\lightgbm\sklearn.py", line 838, in fit
    callbacks=callbacks, init_model=init_model)
  File "D:\Anaconda\lib\site-packages\lightgbm\sklearn.py", line 600, in fit
    callbacks=callbacks, init_model=init_model)
  File "D:\Anaconda\lib\site-packages\lightgbm\engine.py", line 231, in train
    booster = Booster(params=params, train_set=train_set)
  File "D:\Anaconda\lib\site-packages\lightgbm\basic.py", line 1983, in __init__
    train_set.construct()
  File "D:\Anaconda\lib\site-packages\lightgbm\basic.py", line 1325, in construct
    categorical_feature=self.

[LightGBM] [Warning] Accuracy may be bad since you didn't set num_leaves and 2^max_depth > num_leaves
Best: 0.9152210320093532 using {'n_estimators': 150, 'min_child_samples': '20', 'max_depth': 10, 'learning_rate': '0.1'}
Execution time: 28.350897789001465 ms


In [82]:
lgbm_clf_2=LGBMClassifier(n_estimators=200, min_child_samples=10, max_depth=30, learning_rate=0.1)
pred1=lgbm_clf_2.fit(X_train,y_train).predict(X_test)

In [83]:
df2 = pd.DataFrame(data = pred1,columns=["term_deposit_subscribed"])

In [84]:
df2["term_deposit_subscribed"] = df2["term_deposit_subscribed"].astype(int)

In [85]:
sub = pd.concat([sample["id"],df2],axis=1)

In [86]:
sub.to_csv("submission2_bank_marketing.csv",index=False)

In [95]:
#_estimators = [300,150,450,200,500]
max_depth = ["None",4,5,6,7,8,10,20,30,40]
#earning_rate=["0.1","0.2","0.5","0.3","0.01"]
max_features = ["auto",0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
#in_child_samples=["20","10","5","30"]
min_samples_split = [2,5,10,15,20,25]
min_samples_leaf = [1,2,5,10,15]

param_grid = dict(max_depth=max_depth,max_features=max_features,min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf)


In [96]:
import time
rand=RandomizedSearchCV(estimator=tree_clf,param_distributions=param_grid,cv =skfolds)
start_time = time.time()
rand_result = rand.fit(X_train,y_train)

print(f"Best: {rand_result.best_score_} using {rand_result.best_params_}" )
print(f"Execution time: {str((time.time() - start_time))} ms")

D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda\lib\site-packages\sklearn\tree\_classes.py", line 894, in fit
    X_idx_sorted=X_idx_sorted)
  File "D:\Anaconda\lib\site-packages\sklearn\tree\_classes.py", line 276, in fit
    if max_depth <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

  FitFailedWarning)
D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\sklearn\model_selecti

Best: 0.9012228647265145 using {'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.7, 'max_depth': 5}
Execution time: 1.9535813331604004 ms


In [94]:
tree_clf.get_params().keys()

dict_keys(['ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_impurity_split', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'presort', 'random_state', 'splitter'])

In [97]:
tree_clf1 = DecisionTreeClassifier(min_samples_split = 20, min_samples_leaf = 2, max_features = 0.7, max_depth = 5)

In [98]:
pred2=tree_clf1.fit(X_train,y_train).predict(X_test)

In [99]:
df3 = pd.DataFrame(data = pred2,columns=["term_deposit_subscribed"])

In [100]:
df3["term_deposit_subscribed"] = df3["term_deposit_subscribed"].astype(int)

In [101]:
sub = pd.concat([sample["id"],df3],axis=1)

In [102]:
sub.to_csv("submission3_bank_marketing.csv",index=False)

In [104]:
rnd_clf.get_params().keys()

dict_keys(['bootstrap', 'ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'max_samples', 'min_impurity_decrease', 'min_impurity_split', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])

In [109]:
n_estimators = [300,150,450,200,500]
max_depth = ["None",4,5,6,7,8,10,20,30,40]

max_features = ["auto",0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
min_child_samples=["20","10","5","30"]
min_samples_split = [2,5,10,15,20,25]
min_samples_leaf = [1,2,5,10,15]

param_grid = dict(n_estimators = n_estimators,max_depth=max_depth,
                 max_features=max_features,min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf)

In [110]:
import time
rand=RandomizedSearchCV(estimator=rnd_clf,param_distributions=param_grid,cv =skfolds)
start_time = time.time()
rand_result = rand.fit(X_train,y_train)

print(f"Best: {rand_result.best_score_} using {rand_result.best_params_}" )
print(f"Execution time: {str((time.time() - start_time))} ms")

D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "D:\Anaconda\lib\site-packages\joblib\parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "D:\Anaconda\lib\site-packages\joblib\parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "D:\Anaconda\lib\site-packages\joblib\parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "D:\Anaconda\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result =

Best: 0.9112080133977943 using {'n_estimators': 300, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.8, 'max_depth': 30}
Execution time: 298.8360929489136 ms


In [113]:
rnd_clf1 = RandomForestClassifier(n_estimators= 300, min_samples_split= 20, min_samples_leaf= 2, max_features= 0.8, max_depth= 30)

In [114]:
pred3=rnd_clf1.fit(X_train,y_train).predict(X_test)

In [115]:
df4 = pd.DataFrame(data = pred3,columns=["term_deposit_subscribed"])

In [116]:
df4["term_deposit_subscribed"] = df4["term_deposit_subscribed"].astype(int)

In [117]:
sub = pd.concat([sample["id"],df4],axis=1)

In [118]:
sub.to_csv("submission4_bank_marketing.csv",index=False)

In [120]:
hyperparam_combs = {
    'max_depth': [4, 6, 8, 10, 12],
    'criterion': ['gini', 'entropy'],
    'min_samples_split': [2, 10, 20, 30, 40],
    'max_features': [0.2, 0.4, 0.6, 0.8, 1],
    'max_leaf_nodes': [8, 16, 32, 64, 128],
    'class_weight': [{0: 1, 1: 1}, {0: 1, 1: 2}, {0: 1, 1: 3}, {0: 1, 1: 4}, {0: 1, 1: 5}]
}

clf_A = RandomizedSearchCV(DecisionTreeClassifier(),
                         hyperparam_combs,
                         scoring='f1',
                         random_state=1,
                         n_iter=20)
search=clf_A.fit(X_train,y_train)
search.best_params_

{'min_samples_split': 20,
 'max_leaf_nodes': 32,
 'max_features': 0.8,
 'max_depth': 10,
 'criterion': 'gini',
 'class_weight': {0: 1, 1: 3}}

In [121]:
tree_clf2 = DecisionTreeClassifier(min_samples_split= 20,
 max_leaf_nodes = 32,
 max_features= 0.8,
 max_depth= 10,
 criterion= 'gini',
 class_weight= {0: 1, 1: 3})
pred_A=tree_clf2.fit(X_train,y_train).predict(X_test)

In [122]:
df5 = pd.DataFrame(data = pred_A,columns=["term_deposit_subscribed"])

In [123]:
df5["term_deposit_subscribed"] = df5["term_deposit_subscribed"].astype(int)

In [124]:
sub = pd.concat([sample["id"],df5],axis=1)

In [125]:
sub.to_csv("submission5_bank_marketing.csv",index=False)